services:
  frontend: 
    image: frontend:dev
    ports:
      - "8080:8080"
    
    volumes:
      - ./client:/app
      - /app/node_modules
  
  backend:
    image: backend:dev
    ports:
      - "8000:8000"
    
    volumes:
      - ./server:/app
