# Generated by Django 4.1.7 on 2023-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_username_alter_user_role_delete_userrole"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="professor",
        ),
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="section",
            name="teacher",
        ),
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(related_name="courses", to="users.user"),
        ),
        migrations.AddField(
            model_name="section",
            name="assistants",
            field=models.ManyToManyField(related_name="sections", to="users.user"),
        ),
    ]
