# Generated by Django 4.1.7 on 2023-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("0", "Past"), ("1", "Present"), ("2", "Future")], max_length=1
            ),
        ),
    ]
