# Generated by Django 4.1.7 on 2023-03-17 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0003_section"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="professor_id",
            new_name="professor",
        ),
    ]
