# Generated by Django 4.1.7 on 2023-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    (0, "Super Admin"),
                    (1, "Admin"),
                    (2, "Teacher"),
                    (3, "Teaching Assistant"),
                    (4, "Student"),
                ],
                default=4,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
