# Generated by Django 4.1.7 on 2023-03-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_course_professor_remove_course_semester_and_more"),
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture",
            name="video",
        ),
        migrations.AddField(
            model_name="lecture",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.section",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="video_link",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lecture",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
    ]
