# Generated by Django 4.1.7 on 2023-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="video_link",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
