# Generated by Django 4.1.7 on 2023-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[(1, "Student"), (2, "Teaching Assistant"), (3, "Teacher")],
                max_length=1,
                null=True,
            ),
        ),
    ]
